language: bash
services: docker

env:
  - VERSION=1.4.11.1
    BASE=5.6-apache
  - VERSION=1.5.6.3
    BASE=5.6-apache
  - VERSION=1.6.1.24
    BASE=7.0-apache
  - VERSION=1.7.6.3
    BASE=apache

  - VERSION=1.7-5.6-apache
    BASE=5.6-apache
  - VERSION=1.5-7.0-apache
    BASE=7.2-apache
  - VERSION=1.5-7.1-apache
    BASE=7.2-apache
  - VERSION=1.5-7.2-apache
    BASE=7.2-apache

  - VERSION=1.7-5.6-fpm
    BASE=5.6-fpm
  - VERSION=1.5-7.2-fpm
    BASE=7.2-fpm
  - VERSION=1.7.6.3
    BASE=fpm

  - VERSION=nightly-7.3-apache
    BASE=7.3-apache

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="prestashop/prestashop:${VERSION}"
  - image="${image//'/'/-}"

script:
  - docker build -t "prestashop/base:$BASE" base/images/$BASE
  - docker tag prestashop/base:$BASE prestashop/base:5.6-apache
  - docker build -t "$image" images/$VERSION
  - ~/official-images/test/run.sh "$image"
  - docker run -tid --name prestashop $image && docker exec -ti prestashop cat /var/www/html/index.php

after_script:
  - docker images
